routes/web.php
<?php



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('home');
});


 Route::get('map', 'MapController@index')->name('map');
 Route::get('consulta', 'MapController@consulta')->name('consulta');
 Route::get('bitacoras', 'MapController@bitacoras')->name('bitacoras');
 Route::get('bold/{taxon}/{geo}', 'MapController@bold')->name('bold');

 Route::get('bold/{taxon}/{geo}', [
      'uses'=> 'MapController@bold',
      'as'  => 'bold'
  ]);
 Route::get('gestion', function()
  {
   return view('gestion');
  });
  Route::get('quienes_somos', function()
  {
   return view('somos');
  });

Auth::routes();

Route::get('/redirect', 'SocialAuthController@redirect');
Route::get('/callback', 'SocialAuthController@callback');

Route::get('google', function () {
    return view('googleAuth');
});
    
Route::get('auth/google', 'Auth\LoginController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\LoginController@handleGoogleCallback');

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('departamento','DepartamentoController');
    Route::resource('municipio','MunicipioController');
    Route::resource('coleccion','ColeccionController');
    Route::resource('prestatario','PrestatarioController');
    Route::resource('publicacion','PublicacionController');
    Route::resource('aprobacion','AprobacionController');
    Route::resource('zona','ZonaController');
    Route::resource('secuencia','SecuenciaController');
     Route::resource('coleccion','ColeccionController');
 Route::resource('zona','ZonaController');
 Route::resource('dominio','DominioController');
 
 Route::resource('pago','PagoController');
 Route::resource('partidac','PartidacController');
 Route::get('gestionp','PartidacController@gestionp')->name('gestionCierres');
 Route::get('partidas/{id}','PartidacController@partidas')->name('partidasCierres');
 Route::get('libroMayor/{id}','PartidacController@libroMayor')->name('libroMayor');
 Route::get('detallepartida/{id}/{status}','PartidacController@detallepartida')->name('detallePartidas');
 Route::get('balance/{id}','PartidacController@balance')->name('balanceCierres');
 Route::get('balancec','PartidacController@estadoc')->name('reporteBalance');
 Route::get('balancecr','PartidacController@estadocr')->name('reporteBalancer');
 Route::resource('prestamo','PrestamoController');
 Route::resource('prestatario','PrestatarioController');
 Route::resource('contribuyente','ContribuyenteController');
 Route::resource('catcuenta','CatcuentaController');
 Route::resource('contcuenta','ContCuentaController');
 Route::resource('libcompras','LibcomprasController');
 Route::resource('libventascs','LibventascsController');
 Route::resource('libventas','LibventasController');
 Route::resource('contelemento','contElementoController');
 Route::resource('contrubro','contRubroController');
 
 Route::resource('secuencia','SecuenciaController');
 Route::resource('riesgo','RiesgoController');
 Route::resource('tipoInvestigacion','TipoInvestigacionController');
 Route::resource('reino','ReinoController');
 Route::resource('filum','FilumController');
 Route::resource('clase','ClaseController');
 Route::resource('orden','OrdenController');
 Route::resource('especieAmenazada','EspecieAmenazadaController');
 Route::resource('municipio','MunicipioController');
 Route::resource('familia','FamiliaController');
  Route::resource('genero','GeneroController');
  Route::resource('especie','EspecieController');
  Route::resource('especimen','EspecimenController');
  Route::resource('taxonomia','TaxonomiaController');
Route::resource('investigacion','InvestigacionController');

Route::get('facturacion','PagoController@facturacion')->name('pago.facturacion');
Route::get('facturacionccf','PagoController@facturacionccf')->name('pago.facturacionccf');
Route::get('facturacionfe','PagoController@facturacionfe')->name('pago.facturacionfe');
Route::get('facturacionse','PagoController@facturacionse')->name('pago.facturacionse');
Route::get('facturacionnc','PagoController@facturacionnc')->name('pago.facturacionnc');

Route::get('index2','PrestamoController@index2')->name('prestamo.index2');
Route::get('create2','ContCuentaController@create2')->name('contcuenta.create2');
Route::get('create3','ContCuentaController@create3')->name('contcuenta.create3');
Route::get('create4','ContCuentaController@create4')->name('contcuenta.create4');
Route::get('create5','ContCuentaController@create5')->name('contcuenta.create5');
Route::post('store2','ContCuentaController@store2')->name('contcuenta.store2');
Route::post('store3','ContCuentaController@store3')->name('contcuenta.store3');
Route::post('store4','ContCuentaController@store4')->name('contcuenta.store4');
Route::post('store5','ContCuentaController@store5')->name('contcuenta.store5');
Route::get('edit2/{id}','ContCuentaController@edit2')->name('contcuenta.edit2');
Route::get('edit3/{id}','ContCuentaController@edit3')->name('contcuenta.edit3');
Route::get('edit4/{id}','ContCuentaController@edit4')->name('contcuenta.edit4');
Route::get('edit5/{id}','ContCuentaController@edit5')->name('contcuenta.edit5');
Route::post('update2','ContCuentaController@update2')->name('contcuenta.update2');
Route::post('update3','ContCuentaController@update3')->name('contcuenta.update3');
Route::post('update4','ContCuentaController@update4')->name('contcuenta.update4');
Route::post('update5','ContCuentaController@update5')->name('contcuenta.update5');
Route::delete('destroy2/{id}','ContCuentaController@destroy2')->name('contcuenta.destroy2');
Route::delete('destroy3/{id}','ContCuentaController@destroy3')->name('contcuenta.destroy3');
Route::delete('destroy4/{id}','ContCuentaController@destroy4')->name('contcuenta.destroy4');
Route::delete('destroy5/{id}','ContCuentaController@destroy5')->name('contcuenta.destroy5');

Route::get('/get-prestatarios', 'DropdownController@getPrestatarios');
Route::get('/get-prestamos/{prestatario}', 'DropdownController@getPrestamos');


//RUTAS PARA REPORTERIA
Route::get('dominioPrueba.pdf', 'DominioController@generatePDF');

Route::get('partidacPrueba.pdf', 'PartidacController@generatePDF')->name('reportePartidac');
Route::get('partidacPrueba.pdf2', 'PartidacController@generatePDF2')->name('reportePartidacr');
Route::get('partidacPrueba.pdf3/{id}', 'PartidacController@generatePDF3')->name('reportePartidac3');
Route::get('partidacPrueba.pdf4/{id}/{status}', 'PartidacController@generatePDF4')->name('reportePartidac4');
Route::get('libroMayor.pdf5/{id}', 'PartidacController@generatePDF5')->name('libroMayorpdf');
Route::get('partidac.pdf6/{fechai}/{fechaf}/{cuenta}', 'PartidacController@generatePDF6')->name('partidashpdf');
Route::get('/pagoPrueba.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF')->name('reportePago');
Route::get('/pagoPrueba2.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF2')->name('reportePago2');
Route::get('/pagoPrueba3.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF3')->name('reportePago3');
Route::get('/pagoPrueba4.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF4')->name('reportePago4');
Route::get('/pagoPrueba5.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF5')->name('reportePago5');
Route::get('/jsonpago/{idprest}/{fechadepago}', 'PagoController@jsonp')->name('jsonpago');
Route::get('contribuyentePrueba.pdf', 'ContribuyenteController@generatePDF');
Route::get('catcuentaPrueba.pdf', 'CatcuentaController@generatePDF');
Route::get('contcuentaPrueba.pdf', 'ContCuentaController@generatePDF');
Route::get('libcomprasPrueba.pdf', 'LibcomprasController@generatePDF');
Route::get('/prestamoPrueba.pdf/{id}', 'PrestamoController@generatePDF')->name('reportePre');
Route::get('/prestamoPrueba2.pdf/{id}', 'PrestamoController@generatePDF2')->name('reportePre2');

Route::get('/exportPrestamo/{id}', 'PrestamoController@exportExcel')->name('excelPrestamo');
Route::get('/exportLibcompras/{ccf}', 'LibcomprasController@exportExcel')->name('excelLibcompras');
Route::get('/exportLibventascs/{ccf}', 'LibventascsController@exportExcel')->name('excelLibventascs');
Route::get('/detalle/{periodo}', 'LibventasController@detalle')->name('detalleVentas');
Route::get('/exportLibrocuenta/{fechai}/{fechaf}/{cuenta}', 'PartidacController@exportExcelp')->name('excelLibroCuenta');
Route::get('exportPartidac', 'PartidacController@exportExcel')->name('excelPartidac');
Route::get('exportPartidac2', 'PartidacController@exportExcel2')->name('excelPartidacr');
Route::get('cierre', 'PartidacController@cierre')->name('cierre');
Route::get('procesoCierre', 'PartidacController@procesoCierre')->name('procesoCierre');
Route::get('reproceso', 'PartidacController@Reproceso')->name('reproceso');
Route::get('vreproceso', 'PartidacController@Vreproceso')->name('vreproceso');
Route::get('partidash', 'PartidacController@Partidash')->name('historialdePartidas');

Route::get('reportes', 'ReporteController@Index')->name('reportes.index');
Route::get('reportePrestamo.pdf', 'ReporteController@generatePDF')->name('reportePrestamop');
Route::get('exportPrestamo', 'ReporteController@exportExcel')->name('reportePrestamoe');

Route::get('especieAmenazada.pdf', 'EspecieAmenazadaController@generatePDF');
Route::get('reporteTaxonomia.pdf', 'TaxonomiaController@generatePDF');
Route::get('/reportePDF.pdf/{id}', 'EspecimenController@generatePDF');
Route::get('/reporteEspecie/{idReino}', 'EspecieController@reportePDF')->name('reporte2');

resources/views/bold.blade.php
@extends ('layouts.app')
@section('content')
  <div class="row">
    <div class ="col-sm-12">
      <div class="full.right">
      <h2>Dominios</h2>
      <br>
      </div>
    </div>
  </div>
      <br>
  <table class="table table-striped" style="text-align:center" >
    <tr>
      <th with="80px">No</th>
      <th style="text-align:center">Nombre</th>
      <th style="text-align:center">Acciones</th>
    </tr>
    <?php
    //var_dump($response);
    $src = $response->bold_records->records;
    $seq = $response->bold_records->records;
    ?> 
    @foreach ($src as $value)
    <?php
    //$seq = $response->bold_records->records->sequences->sequence;
    //var_dump($seq);
    ?>    
        <tr>
        <td>{{ $value->record_id }}</td>
        <td>{{ $value->specimen_identifiers->institution_storing }}</td>
        <td>{{ $value->taxonomy->phylum->taxon->name }}</td>
      </tr>
    @endforeach
  </table>
 <div class="text-center">
    <a class="btn btn-primary" href="#">Regresar</a>
 </div>
@endsection

resources/views/dropdowns.blade.php
<select id="prestatarioSelect" name="idprest" class="form-control" data-live-search="true">
    <option value="">Seleccionar Prestatario</option>
</select>

<br>
<select id="prestamoSelect" name="idprest2" class="form-control" data-live-search="true">
    <option value="">Seleccionar Prestamo</option>
</select>

<script type="text/javascript">
$(document).ready(function () {
    // Populate categories dropdown
    $.get('/get-prestatarios', function (data) {
        $.each(data, function (key, value) {
            $('#prestatarioSelect').append('<option value="' + value.id + '">' + value.pnombre + ' ' + value.snombre + ' ' + value.papellido + ' ' + value.sapellido + '</option>');
        });
    });

    // Handle category selection change
    $('#prestatarioSelect').change(function () {
        var selectedPrestatario = $(this).val();
        $('#prestamoSelect').empty();

        if (selectedPrestatario !== '') {
            // Populate products dropdown based on selected category
            $.get('/get-prestamos/' + selectedPrestatario, function (data) {
                $.each(data, function (key, value) {
                    $('#prestamoSelect').append('<option value="' + value.id + '">' + value.id + ' ' + '-' + value.codigoPrestamo + '</option>');
                });
            });
        }
    });
});

</script>

resources/views/gestion1.blade.php
@extends('layouts.app')

@section('content')
<header class="bg-primary text-white">
            <div class="container text-center">
                <h1>Welcome to Scrolling Nav</h1>
                <p class="lead">A landing page template freshly redesigned for Bootstrap 4</p>
            </div>
        </header>
        <section id="about">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <h2>About this page</h2>
                        <p class="lead">This is a great place to talk about your webpage. This template is purposefully unstyled so you can use it as a boilerplate or starting point for you own landing page designs! This template features:</p>
                        <ul>
                            <li>Clickable nav links that smooth scroll to page sections</li>
                            <li>Responsive behavior when clicking nav links perfect for a one page website</li>
                            <li>Bootstrap's scrollspy feature which highlights which section of the page you're on in the navbar</li>
                            <li>Minimal custom CSS so you are free to explore your own unique design options</li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <section class="bg-light" id="services">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <h2>Services we offer</h2>
                        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut optio velit inventore, expedita quo laboriosam possimus ea consequatur vitae, doloribus consequuntur ex. Nemo assumenda laborum vel, labore ut velit dignissimos.</p>
                    </div>
                </div>
            </div>
        </section>
        <section id="contact">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <h2>Contact us</h2>
                        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.</p>
                    </div>
                </div>
            </div>
        </section>
@endsection

resources/views/gestion2.blade.php
@extends('layouts.app')

@section('content')
    <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-ex1-collapse">
      <span class="sr-only">Desplegar navegación</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url('/gestion') }}">MENU</a>
  </div>
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="nav-item dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Especies
        </a>
        <ul class="dropdown-menu">
          <li><a href="{{ route('dominio.index') }}">Gestión de Dominios </a></li>
          <li><a href="{{ route('reino.index') }}">Gestión de Reinos </a></li>
          <li><a href="{{ route('filum.index') }}">Gestión de Filums </a></li>
          <li><a href="{{ route('clase.index') }}">Gestión de Clases</a></li>
          <li><a href="{{ route('orden.index') }}">Gestión de Orden</a></li>
          <li><a href="{{ route('familia.index') }}">Gestión de Familias</a></li>
          <li><a href="{{ route('genero.index') }}">Gestión de Géneros</a></li>
          <li><a href="{{ route('especie.index') }}">Gestión de Especies</a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav">
      <li class="nav-item dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Colecciones
        </a>
        <ul class="dropdown-menu">
          <li><a href="{{ route('taxonomia.index') }}">Taxonomias</a></li>
         <li><a href="{{ route('especimen.index') }}">Especímenes</a></li>
        </ul>
      </li>
    </ul>
  </div>  
   </div>
 </nav>
        <br>
        <div class="row">
          <div class="col-sm-5">
             <div class="text-left">
                <h2><strong>BIENVENIDO / A</strong></h2>
              </div>
              <br>
              <br>
              <div class="text-left">
                <h4>Tu plataforma completa de acceso a la información sobre las especies de la Biodiversidad salvadoreña.</h4>
                <br>
                <h4>BIO-UES  es una plataforma para el almacenamiento de datos sobre las especies naturales administrado por la Escuela de Biología de la Universidad de El Salvador.  </h4>
              </div>
          </div>
         <div class="col-sm-6">
           <div class="text-right">
                    <img src="{{URL::asset('/img/torogoz.jpg')}}" alt="profile Pic" height="350" width="450">
              
                </div>
        </div>
         </div>
           
         

          
                
            </div>

@endsection

resources/views/layouts.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>EM&ASOCIADOS</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet"> 
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
    <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{ url('/home') }}">
    <img src="startbootstrap-clean-blog-gh-pages/assets/img/logo.jpg" width="70" height="70" class="d-inline-block align-top" alt="">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">EM&ASOCIADOS</a>
      </li>

      @can('Dominios')
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Contabilidad
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          @can('Dominios')
          <a class="dropdown-item" href="{{ route('contribuyente.index') }}">Gestión de Contribuyentes</a>
          @endcan
          @can('Dominios')
          <a class="dropdown-item" href="{{ route('catcuenta.index') }}">Gestión de Cuentas</a>
          @endcan
          @can('Dominios')
          <a class="dropdown-item" href="{{ route('libcompras.index') }}">Gestión de Compras</a>
          @endcan
          
        </div>
      </li>
      @endcan

      <!--<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Colecciones
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          @can('Colecciones')
          <a class="dropdown-item"  href="{{ route('coleccion.index') }}">Colecciones</a>
          <a class="dropdown-item"  href="{{ route('prestatario.index') }}">Prestatarios</a>
          @endcan
          @can('Taxonomias')
          <a class="dropdown-item"  href="{{ route('taxonomia.index') }}">Taxonomias</a>
          @endcan
          @can('Especimenes')
          <a class="dropdown-item" href="{{ route('especimen.index') }}">Especímenes</a>
          @endcan
        </div>
      </li>
@can('Investigaciones')
 <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Investigaciones
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"  href="{{ route('investigacion.index') }}"> Gestión de Investigaciones</a>
        @can('TiposInvestigaciones')
         <a class="dropdown-item"  href="{{ route('tipoInvestigacion.index') }}"> Gestión Tipo de Investigaciones</a>
         @endcan
         @can('Publicaciones')
         <a class="dropdown-item"  href="{{ route('publicacion.index') }}"> Gestión Publicaciones</a>
         @endcan
          </div>
      </li>
@endcan

 <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Datos Estadisticos
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"  href="{{ route('especieAmenazada.index') }}"> Especies Amenazadas</a>
          <a class="dropdown-item"  href="{{ route('riesgo.index') }}"> Gestión de Riesgos</a>
          <a class="dropdown-item"  href="{{ route('zona.index') }}"> Gestión de Zonas</a>
         <a class="dropdown-item"  href="{{ route('departamento.index') }}"> Gestión de Departamentos</a>
         <a class="dropdown-item"  href="{{ route('municipio.index') }}"> Gestión de Municipios</a>
          </div>
      </li>

<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Barcoding
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          @can('Secuencias')
          <a class="dropdown-item"  href="{{ route('secuencia.index') }}"> Secuenciación</a>
          @endcan
          <a class="dropdown-item"  href="https://www.boldsystems.org/index.php/Public_BINSearch?searchtype=records"> Bold System</a>
          </div>
      </li>
-->
      @can('Usuarios')
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Gestion Usuarios
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          @can('Usuarios')
          <a class="dropdown-item"  href="{{ route('users.index') }}"> Usuarios</a>
          @endcan
          @can('Roles')
          <a class="dropdown-item"  href="{{ route('roles.index') }}"> Roles</a>
          @endcan
          <a class="dropdown-item"  href="{{ route('bitacoras') }}"> Bitacoras</a>
          </div>
      </li>
      @endcan
      
    </ul>
  </div>
  <ul class="navbar-nav mr-nav">
  @if (Auth::guest())
                    <li class="nav-item"><a class="nav-link" href="{{ url('/login') }}">Entrar</a></li>                   
  @else
            <li class="nav-item dropdown"> 
                <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Usuario: {{ Auth::user()->name }}</a>
               <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                   <a class="dropdown-item" href="{{ url('/home') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">Cerrar Sesión</a>
               </div>
               <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
            </form>
                
            </li>
           
            
@endif
</ul>
</nav>
     
    @yield("header")
        <!-- Main Content-->
    
      <div class="container">
         @yield("container")
          @include('sweetalert::alert')
        <hr />
</div>
        <!-- Footer-->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-youtube fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-muted">Copyright &copy; EM & Asociados 2023</p>
                    </div>
                </div>
            </div>
            <div>
                <nav class="navbar navbar-expand-lg fixed-bottom" style="background-color: #D7D2D1 ;">
        <a class="navbar-brand"> EM & Asociados </a>
            <div >&emsp;<span class="glyphicon glyphicon-copyright-mark"><span id= "fecha"></span></div>
             </nav>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
         <script>
        var f=new Date();
        var fecha = f.getDate() + '-' + (f.getMonth() + 1) + '-' +f.getFullYear();
        var hora = f.getHours() + ':' + f.getMinutes();
        var fechaYhora = fecha + ' , '+hora;
        document.getElementById('fecha').innerHTML = fechaYhora;

</script>
    </body>
</html>