routes/web.php
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('home');
});


 Route::get('map', 'MapController@index')->name('map');
 Route::get('consulta', 'MapController@consulta')->name('consulta');
 Route::get('bitacoras', 'MapController@bitacoras')->name('bitacoras');
 Route::get('bold/{taxon}/{geo}', 'MapController@bold')->name('bold');

 Route::get('bold/{taxon}/{geo}', [
      'uses'=> 'MapController@bold',
      'as'  => 'bold'
  ]);
 Route::get('gestion', function()
  {
   return view('gestion');
  });
  Route::get('quienes_somos', function()
  {
   return view('somos');
  });

Auth::routes();

Route::get('/redirect', 'SocialAuthController@redirect');
Route::get('/callback', 'SocialAuthController@callback');

Route::get('google', function () {
    return view('googleAuth');
});
    
Route::get('auth/google', 'Auth\LoginController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\LoginController@handleGoogleCallback');

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('departamento','DepartamentoController');
    Route::resource('municipio','MunicipioController');
    Route::resource('coleccion','ColeccionController');
    Route::resource('prestatario','PrestatarioController');
    Route::resource('publicacion','PublicacionController');
    Route::resource('aprobacion','AprobacionController');
    Route::resource('zona','ZonaController');
    Route::resource('secuencia','SecuenciaController');
     Route::resource('coleccion','ColeccionController');
 Route::resource('zona','ZonaController');
 Route::resource('dominio','DominioController');
 
 Route::resource('pago','PagoController');
 Route::resource('partidac','PartidacController');
 Route::get('gestionp','PartidacController@gestionp')->name('gestionCierres');
 Route::get('partidas/{id}','PartidacController@partidas')->name('partidasCierres');
 Route::get('libroMayor/{id}','PartidacController@libroMayor')->name('libroMayor');
 Route::get('detallepartida/{id}/{status}','PartidacController@detallepartida')->name('detallePartidas');
 Route::get('balance/{id}','PartidacController@balance')->name('balanceCierres');
 Route::get('balancec','PartidacController@estadoc')->name('reporteBalance');
 Route::get('balancecr','PartidacController@estadocr')->name('reporteBalancer');
 Route::resource('prestamo','PrestamoController');
 Route::resource('prestatario','PrestatarioController');
 Route::resource('contribuyente','ContribuyenteController');
 Route::resource('catcuenta','CatcuentaController');
 Route::resource('contcuenta','ContCuentaController');
 Route::resource('libcompras','LibcomprasController');
 Route::resource('libventascs','LibventascsController');
 Route::resource('libventas','LibventasController');
 Route::resource('contelemento','contElementoController');
 Route::resource('contrubro','contRubroController');
 
 Route::resource('secuencia','SecuenciaController');
 Route::resource('riesgo','RiesgoController');
 Route::resource('tipoInvestigacion','TipoInvestigacionController');
 Route::resource('reino','ReinoController');
 Route::resource('filum','FilumController');
 Route::resource('clase','ClaseController');
 Route::resource('orden','OrdenController');
 Route::resource('especieAmenazada','EspecieAmenazadaController');
 Route::resource('municipio','MunicipioController');
 Route::resource('familia','FamiliaController');
  Route::resource('genero','GeneroController');
  Route::resource('especie','EspecieController');
  Route::resource('especimen','EspecimenController');
  Route::resource('taxonomia','TaxonomiaController');
Route::resource('investigacion','InvestigacionController');

Route::get('facturacion','PagoController@facturacion')->name('pago.facturacion');
Route::get('facturacionccf','PagoController@facturacionccf')->name('pago.facturacionccf');
Route::get('facturacionfe','PagoController@facturacionfe')->name('pago.facturacionfe');
Route::get('facturacionse','PagoController@facturacionse')->name('pago.facturacionse');
Route::get('facturacionnc','PagoController@facturacionnc')->name('pago.facturacionnc');

Route::get('index2','PrestamoController@index2')->name('prestamo.index2');
Route::get('create2','ContCuentaController@create2')->name('contcuenta.create2');
Route::get('create3','ContCuentaController@create3')->name('contcuenta.create3');
Route::get('create4','ContCuentaController@create4')->name('contcuenta.create4');
Route::get('create5','ContCuentaController@create5')->name('contcuenta.create5');
Route::post('store2','ContCuentaController@store2')->name('contcuenta.store2');
Route::post('store3','ContCuentaController@store3')->name('contcuenta.store3');
Route::post('store4','ContCuentaController@store4')->name('contcuenta.store4');
Route::post('store5','ContCuentaController@store5')->name('contcuenta.store5');
Route::get('edit2/{id}','ContCuentaController@edit2')->name('contcuenta.edit2');
Route::get('edit3/{id}','ContCuentaController@edit3')->name('contcuenta.edit3');
Route::get('edit4/{id}','ContCuentaController@edit4')->name('contcuenta.edit4');
Route::get('edit5/{id}','ContCuentaController@edit5')->name('contcuenta.edit5');
Route::post('update2','ContCuentaController@update2')->name('contcuenta.update2');
Route::post('update3','ContCuentaController@update3')->name('contcuenta.update3');
Route::post('update4','ContCuentaController@update4')->name('contcuenta.update4');
Route::post('update5','ContCuentaController@update5')->name('contcuenta.update5');
Route::delete('destroy2/{id}','ContCuentaController@destroy2')->name('contcuenta.destroy2');
Route::delete('destroy3/{id}','ContCuentaController@destroy3')->name('contcuenta.destroy3');
Route::delete('destroy4/{id}','ContCuentaController@destroy4')->name('contcuenta.destroy4');
Route::delete('destroy5/{id}','ContCuentaController@destroy5')->name('contcuenta.destroy5');

Route::get('/get-prestatarios', 'DropdownController@getPrestatarios');
Route::get('/get-prestamos/{prestatario}', 'DropdownController@getPrestamos');


//RUTAS PARA REPORTERIA
Route::get('dominioPrueba.pdf', 'DominioController@generatePDF');

Route::get('partidacPrueba.pdf', 'PartidacController@generatePDF')->name('reportePartidac');
Route::get('partidacPrueba.pdf2', 'PartidacController@generatePDF2')->name('reportePartidacr');
Route::get('partidacPrueba.pdf3/{id}', 'PartidacController@generatePDF3')->name('reportePartidac3');
Route::get('partidacPrueba.pdf4/{id}/{status}', 'PartidacController@generatePDF4')->name('reportePartidac4');
Route::get('libroMayor.pdf5/{id}', 'PartidacController@generatePDF5')->name('libroMayorpdf');
Route::get('partidac.pdf6/{fechai}/{fechaf}/{cuenta}', 'PartidacController@generatePDF6')->name('partidashpdf');
Route::get('/pagoPrueba.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF')->name('reportePago');
Route::get('/pagoPrueba2.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF2')->name('reportePago2');
Route::get('/pagoPrueba3.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF3')->name('reportePago3');
Route::get('/pagoPrueba4.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF4')->name('reportePago4');
Route::get('/pagoPrueba5.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF5')->name('reportePago5');
Route::get('/jsonpago/{idprest}/{fechadepago}', 'PagoController@jsonp')->name('jsonpago');
Route::get('contribuyentePrueba.pdf', 'ContribuyenteController@generatePDF');
Route::get('catcuentaPrueba.pdf', 'CatcuentaController@generatePDF');
Route::get('contcuentaPrueba.pdf', 'ContCuentaController@generatePDF');
Route::get('libcomprasPrueba.pdf', 'LibcomprasController@generatePDF');
Route::get('/prestamoPrueba.pdf/{id}', 'PrestamoController@generatePDF')->name('reportePre');
Route::get('/prestamoPrueba2.pdf/{id}', 'PrestamoController@generatePDF2')->name('reportePre2');

Route::get('/exportPrestamo/{id}', 'PrestamoController@exportExcel')->name('excelPrestamo');
Route::get('/exportLibcompras/{ccf}', 'LibcomprasController@exportExcel')->name('excelLibcompras');
Route::get('/exportLibventascs/{ccf}', 'LibventascsController@exportExcel')->name('excelLibventascs');
Route::get('/detalle/{periodo}', 'LibventasController@detalle')->name('detalleVentas');
Route::get('/exportLibrocuenta/{fechai}/{fechaf}/{cuenta}', 'PartidacController@exportExcelp')->name('excelLibroCuenta');
Route::get('exportPartidac', 'PartidacController@exportExcel')->name('excelPartidac');
Route::get('exportPartidac2', 'PartidacController@exportExcel2')->name('excelPartidacr');
Route::get('cierre', 'PartidacController@cierre')->name('cierre');
Route::get('procesoCierre', 'PartidacController@procesoCierre')->name('procesoCierre');
Route::get('reproceso', 'PartidacController@Reproceso')->name('reproceso');
Route::get('vreproceso', 'PartidacController@Vreproceso')->name('vreproceso');
Route::get('partidash', 'PartidacController@Partidash')->name('historialdePartidas');

Route::get('reportes', 'ReporteController@Index')->name('reportes.index');
Route::get('reportePrestamo.pdf', 'ReporteController@generatePDF')->name('reportePrestamop');
Route::get('exportPrestamo', 'ReporteController@exportExcel')->name('reportePrestamoe');

Route::get('especieAmenazada.pdf', 'EspecieAmenazadaController@generatePDF');
Route::get('reporteTaxonomia.pdf', 'TaxonomiaController@generatePDF');
Route::get('/reportePDF.pdf/{id}', 'EspecimenController@generatePDF');
Route::get('/reporteEspecie/{idReino}', 'EspecieController@reportePDF')->name('reporte2');
Route::get('index_filter', 'EspecieController@index');
//Route::get('reporte2.pdf', 'EspecieController@reportePDF');

app/Especie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class Especie extends Model
{

  use LogsActivity;
  
    protected $fillable = ['idGenero', 'nombreEspecie', 'idReino'];
    protected $dates = ['created_at','updated_at'];

    public function scopeNombre($query, $nombreEspecie)
	{
		return $query->where('nombreEspecie', 'LIKE', "%$nombreEspecie%");
	}

   public function Genero(){
    return $this->belongsTo('App\Genero', 'idGenero');
   }

  public function Familia(){
    return $this->belongsTo('App\Familia', 'idFamilia');
   }
   public function Orden(){
    return $this->belongsTo('App\Orden', 'idOrden');
   }

  public function Clase(){
    return $this->belongsTo('App\Clase', 'idClase');
   }

    public function Filum(){
    return $this->belongsTo('App\Filum', 'idFilum');
   }

	public function Reino(){
    return $this->belongsTo('App\Reino', 'idReino');
   }

	public function Dominio(){
    return $this->belongsTo('App\Dominio', 'idDominio');
}
}

app/Http/Controllers/EspecieController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Input;
use App\Dominio;
use App\Reino;
use App\Filum;
use App\Clase;
use App\Orden;
use App\Familia;
use App\Genero;
use App\Especie;
use Especie1\http\Request\ClaseRequest;
use RealRashid\SweetAlert\Facades\Alert;
use PDF;
use DB;
use Carbon\Carbon;

class EspecieController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:Especies|Crear Especie|Editar Especie|Eliminar Especie', ['only' => ['index','store']]);
         $this->middleware('permission:Crear Especie', ['only' => ['create','store']]);
         $this->middleware('permission:Editar Especie', ['only' => ['edit','update']]);
         $this->middleware('permission:Eliminar Especie', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)

    {
        $idReino=$request->get('idReino');
       $generos = Genero::all();
       $especies = Especie::all();
       $reinos = Reino::all();
       $nombre=$request->get('nombreEspecie');


        if ($idReino != "") {
               
             $especies = Especie::orderBy('id','DESC')->nombre($nombre)->paginate(10);
        return view('especie.index_filter',compact('especies','generos','reinos','idReino'));
            }
        else{
           $especies = Especie::orderBy('id','DESC')->nombre($nombre)->paginate(10);
        return view('especie.index',compact('especies','generos','reinos','idReino'));
            } 
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function create()
    {

        $especies = Especie::all();
        $generos = Genero::all();
        return view('especie.create', compact('generos','especies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
          'idGenero'=>'required|numeric',  
          'nombreEspecie'=>'required|alpha_spaces',
           'idReino', 
          ]);
            Especie::create($request->all());
            Alert::success('Especie agregado con éxito');
        return redirect()->route('especie.index');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $especies = Especie::find($id);
        $date=new Carbon();
        $fecha = $date->format('d-m-Y');

        $pdf = PDF::loadView('especie.reportePDF',compact('especies','fecha'));
        $pdf->getDomPDF()->set_option("enable_php", TRUE);
        return $pdf->stream('reportePDF.pdf');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($idEspecie)
    {
       
        $generos = Genero::all();
        $especies = Especie::find($idEspecie);
        return view('especie.edit',compact('especies','generos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $idEspecie)
    {
        $this->validate($request,[
          'idGenero'=>'required|numeric',  
          'nombreEspecie'=>'required|alpha_spaces',
          'idReino',  
          ]);
        Especie::find($idEspecie)->update($request->all());
        Alert::success('Especie actualizada con éxito');
        return redirect()->route('especie.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($idEspecie)
    {
        try{
             Especie::find($idEspecie)->delete();
             Alert::success('Especie eliminado con exito');
        return redirect()->route('especie.index');
    }catch (\Illuminate\Database\QueryException $e) {
    	Alert::danger('No se Puede eliminar este registro porque esta asociado a otros datos');
        return redirect()->route('especie.index');
    }
    }
    
    public function reportePDF( request $request, $idReino)

    {
        if ($idReino != NULL) {
        $generos = Genero::all();
        $especies = Especie::all();
        $reinos = Reino::all();
        $nombre =$request->get('nombreEspecie');
        $nombreReino= DB::table('reinos')->select('nombreReino')->where('id', $idReino)->get();
        $especies = Especie::orderBy('id','DESC')->nombre($nombre)->paginate(15);
        $date=new Carbon();
        $fecha = $date->format('d-m-Y');
        $pdf = PDF::loadView('especie.reporte2',compact('especies','fecha','idReino','nombreReino'));
        $pdf->getDomPDF()->set_option("enable_php", TRUE);
        return $pdf->stream('reporteEspecie.pdf');
        }
        else {
            Alert::danger('Seleccione un reino');
             return redirect()->route('especie.index');
        }
        
        
        
    }

}

resources/views/especie/edit.blade.php
@extends('layouts.app')
@section('content')
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    	<h3 style="text-align:center"> ACTUALIZACION DE DATOS DE ESPECIE</h3>
    	<br>
      {{ Form::model($especies,['route'=>['especie.update',$especies->id],'method'=>'PATCH']) }}
      @include('especie.form_master')
      {{ Form::close() }}
    </div>
  </div>
@endsection

resources/views/especie/form_master.blade.php
<div class="row">
  <br>
     <div class="col-sm-5">
       {!! form::label('Ingrese nombre de la especie') !!}
      <div class="form-horizontal {{ $errors->has('nombreEspecie') ? 'has-error' : "" }}">
            <i> {{ Form::text('nombreEspecie',NULL, ['class'=>'form-control','id'=>'nombre','placeholder'=>'Nombre de la Especie']) }}  </i> 
            <div class="help-block" > 
          {{ $errors->first('nombreEspecie', 'Ingrese los datos correctamente') }}
      </div>
      </div>
      </div>
      
     <div class="col-sm-5">
      <div class="form-horizontal {{ $errors->has('idGenero') ? 'has-error' : "" }}">
        {!! form::label('Seleccione el género:') !!}
   
      <select name="idGenero" class="form-control" onchange="reino()">
                <option disabled selected>Seleccione género </option>
                   @foreach($generos as $genero)  
                      <option value="{{$genero->id}}">{{$genero->nombreGenero}}</option>
                @endforeach
            </select>
      
          <div class="help-block" > 
          {{ $errors->first('idGenero', 'Debe seleccionar una opción') }}
      </div>          
 </div>
</div>

        <div>
        <br>
        {{ Form::button(isset($model)? 'Update' : 'Guardar' , ['class'=>'btn btn-success btn-sm','type'=>'submit']) }}
        <a class="btn btn-danger btn-sm" href="{{ route('especie.index') }}">Cancelar</a>
      </div>
      
    </div>
     
      <br>
 

resources/views/especie/index.blade.php
@extends ('layout')
@section('header')
<header style="background-image: url('startbootstrap-clean-blog-gh-pages/assets/img/titulos.jpg'); opacity: 0.8;"> <h2 style="color: white; font-family: sans-serif; font-size: 58px; text-align: center;">Especies</h2>
  </header>
@endsection
@section('container')
 
  @if ($errors->any())
   <div class="alert alert-danger">
  
          <p>Debe ingresar datos válidos</p>
     
   </div>
  @endif
  <br>
  <div class="row">
     <div class="col-md-8">
      @can('Crear Especie')
        <a id='btnAgregar' onclick="mostrarFormulario()" class="btn btn-success btn-lg">
            Nueva Especie
        </a>
        @endcan
        <br>
        <br>
              {{ Form::open(['route'=>'especie.store', 'method'=>'POST', 'class'=>'agregar']) }}
             @include('especie.form_master')
             {{ form::close() }}
        
      </div>
       <div class="col-md-4">
         {!! Form::open(['route'=>'especie.index', 'method'=>'GET', 'class'=>'navbar-form pull-right', 'role'=>'search'])!!}
        <div class="input-group"> 
           {!! Form::text('nombreEspecie', null, ['class'=>'form-control', 'placeholder'=>'Buscar'])!!}
           <button type="submit" class="btn-secondary btn-sm" data-toggle="tooltip" data-placement="top" title="Buscar">Buscar</button>
        {!! Form::close()!!}
        </div>
        <br>
      
      </div>
  </div>
  <div class="row"> 
          <div>
              <br>
               {!! Form::open(['route'=>'especie.index', 'method'=>'GET'])!!}
              <div class="input-group col-md-12">
                <select name="idReino" id="idReino" class="form-control">
                <option disabled selected>Seleccione reino </option>
                @foreach($reinos as $reino)
                      <option value="{{$reino->id}}">{{$reino->nombreReino}}</option>
                       
                 @endforeach
           </select>
             <div class="col-md-3">
              <button type="submit" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Buscar" id="buscar">Filtrar especies</button>
                 </div>
            <div class="col-md-3">
                {!! link_to_action('EspecieController@reportePDF','reporte pdf',[$idReino], $attributes = array('class' => 'btn btn-info btn-sm', 'target' =>'_blank')) !!}
            
            </div>
             
       
           
              </div>
              
              {!! Form::close()!!}
            </div> 
                   
  </div>
   
      <br>
  <table class="table table-striped" style="text-align:center" >
    <tr>
      <th with="80px">No</th>
      <th style="text-align:center">Dominio</th>
      <th style="text-align:center">Reino</th>
      <th style="text-align:center">Filum</th>
      <th style="text-align:center">Clase</th>
      <th style="text-align:center">Orden</th>
      <th style="text-align:center">Familia</th>
      <th style="text-align:center">Genero</th>
      <th style="text-align:center">Especie</th>
      <th style="text-align:center">Acciones</th>
    </tr>
    <?php $no=1; ?>
      <?php $no=1; ?>
    @foreach ($especies as $key => $value).

    <tr>
        <td>{{$no++}}</td>
        <td>{{$value->Genero->Familia->Orden->Clase->Filum->Reino->Dominio->nombreDominio}}</td>
        <td>{{$value->Genero->Familia->Orden->Clase->Filum->Reino->nombreReino}}</td>
        <td>{{$value->Genero->Familia->Orden->Clase->Filum->nombreFilum}}</td>
        <td>{{$value->Genero->Familia->Orden->Clase->nombreClase}}</td>
        <td>{{$value->Genero->Familia->Orden->nombreOrden}}</td>
        <td>{{$value->Genero->Familia->nombreFamilia}}</td>
        <td>{{$value->Genero->nombreGenero }}</td>
        <td>{{$value->nombreEspecie }}<br></td>
        <td>
          <a class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="top" title="Detalles" href="{{route('especie.show',$value->id)}}" target="_blank">
              <i class="glyphicon glyphicon-list-alt">Detalles PDF</i></a>
               
          @can('Editar Especie')
          <a class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Editar" href="{{route('especie.edit',$value->id)}}">
              <i class="glyphicon glyphicon-pencil">Editar</i></a>
          @endcan
          @can('Eliminar Especie')
            {!! Form::open(['method' => 'DELETE','route' => ['especie.destroy', $value->id],'style'=>'display:inline', 'class'=>'formulario-eliminar']) !!}
              <button type="submit" data-toggle="tooltip" data-placement="top" title="Eliminar" style="display: inline;" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash" >Eliminar</i></button>
            {!! Form::close() !!}
          @endcan
        </td>
      </tr>
    @endforeach
  </table>
  {!! $especies->appends(Request::only(['idReino'=>'idReino']))->render() !!} 
  
 <div class="text-center">
    <a class="btn btn-primary" href="{{ url('/gestion') }}">Regresar</a>
  </div>

<!--Script para mostrar formulario y Alerta confirmar Guardar con ajax-->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script type="text/javascript">
      $('.agregar2').hide();
       function mostrarFormulario2(){
        $('.agregar2').show();
       }
      $('.agregar').hide();
       function mostrarFormulario(){
        $('.agregar').show();
       }
$('.agregar').submit(function(e){
     e.preventDefault();Swal.fire({
  title: '¿Está seguro de guardar esta especie?',
  showDenyButton: true,
  //showCancelButton: true,
  confirmButtonText: `Guardar`,
  denyButtonText: `Cancelar`,
})
     .then((result) => {
    if (result.isConfirmed) {
     this.submit();
    }
})
});

    </script>

  
<!--Script para Alerta confirmar eliminar con ajax-->

 <script type="text/javascript">
$('.formulario-eliminar').submit(function(e){
     e.preventDefault();
       Swal.fire({
    title: '¿Está seguro de eliminar permanentemente esta Especie?',
    icon: 'warning',
    showCancelButton: true,
    confirmButtonColor: '#3085d6',
    cancelButtonColor: '#d33',
    confirmButtonText: 'Eliminar',
    cancelButtonText: 'Cancelar'

  }).then((result) => {
    if (result.isConfirmed) {
     this.submit();
    }
})
});
    </script>

    
@endsection