routes/web.php
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('home');
});


 Route::get('map', 'MapController@index')->name('map');
 Route::get('consulta', 'MapController@consulta')->name('consulta');
 Route::get('bitacoras', 'MapController@bitacoras')->name('bitacoras');
 Route::get('bold/{taxon}/{geo}', 'MapController@bold')->name('bold');

 Route::get('bold/{taxon}/{geo}', [
      'uses'=> 'MapController@bold',
      'as'  => 'bold'
  ]);
 Route::get('gestion', function()
  {
   return view('gestion');
  });
  Route::get('quienes_somos', function()
  {
   return view('somos');
  });

Auth::routes();

Route::get('/redirect', 'SocialAuthController@redirect');
Route::get('/callback', 'SocialAuthController@callback');

Route::get('google', function () {
    return view('googleAuth');
});
    
Route::get('auth/google', 'Auth\LoginController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\LoginController@handleGoogleCallback');

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('departamento','DepartamentoController');
    Route::resource('municipio','MunicipioController');
    Route::resource('coleccion','ColeccionController');
    Route::resource('prestatario','PrestatarioController');
    Route::resource('publicacion','PublicacionController');
    Route::resource('aprobacion','AprobacionController');
    Route::resource('zona','ZonaController');
    Route::resource('secuencia','SecuenciaController');
     Route::resource('coleccion','ColeccionController');
 Route::resource('zona','ZonaController');
 Route::resource('dominio','DominioController');
 
 Route::resource('pago','PagoController');
 Route::resource('partidac','PartidacController');
 Route::get('gestionp','PartidacController@gestionp')->name('gestionCierres');
 Route::get('partidas/{id}','PartidacController@partidas')->name('partidasCierres');
 Route::get('libroMayor/{id}','PartidacController@libroMayor')->name('libroMayor');
 Route::get('detallepartida/{id}/{status}','PartidacController@detallepartida')->name('detallePartidas');
 Route::get('balance/{id}','PartidacController@balance')->name('balanceCierres');
 Route::get('balancec','PartidacController@estadoc')->name('reporteBalance');
 Route::get('balancecr','PartidacController@estadocr')->name('reporteBalancer');
 Route::resource('prestamo','PrestamoController');
 Route::resource('prestatario','PrestatarioController');
 Route::resource('contribuyente','ContribuyenteController');
 Route::resource('catcuenta','CatcuentaController');
 Route::resource('contcuenta','ContCuentaController');
 Route::resource('libcompras','LibcomprasController');
 Route::resource('libventascs','LibventascsController');
 Route::resource('libventas','LibventasController');
 Route::resource('contelemento','contElementoController');
 Route::resource('contrubro','contRubroController');
 
 Route::resource('secuencia','SecuenciaController');
 Route::resource('riesgo','RiesgoController');
 Route::resource('tipoInvestigacion','TipoInvestigacionController');
 Route::resource('reino','ReinoController');
 Route::resource('filum','FilumController');
 Route::resource('clase','ClaseController');
 Route::resource('orden','OrdenController');
 Route::resource('especieAmenazada','EspecieAmenazadaController');
 Route::resource('municipio','MunicipioController');
 Route::resource('familia','FamiliaController');
  Route::resource('genero','GeneroController');
  Route::resource('especie','EspecieController');
  Route::resource('especimen','EspecimenController');
  Route::resource('taxonomia','TaxonomiaController');
Route::resource('investigacion','InvestigacionController');

Route::get('facturacion','PagoController@facturacion')->name('pago.facturacion');
Route::get('facturacionccf','PagoController@facturacionccf')->name('pago.facturacionccf');
Route::get('facturacionfe','PagoController@facturacionfe')->name('pago.facturacionfe');
Route::get('facturacionse','PagoController@facturacionse')->name('pago.facturacionse');
Route::get('facturacionnc','PagoController@facturacionnc')->name('pago.facturacionnc');

Route::get('index2','PrestamoController@index2')->name('prestamo.index2');
Route::get('create2','ContCuentaController@create2')->name('contcuenta.create2');
Route::get('create3','ContCuentaController@create3')->name('contcuenta.create3');
Route::get('create4','ContCuentaController@create4')->name('contcuenta.create4');
Route::get('create5','ContCuentaController@create5')->name('contcuenta.create5');
Route::post('store2','ContCuentaController@store2')->name('contcuenta.store2');
Route::post('store3','ContCuentaController@store3')->name('contcuenta.store3');
Route::post('store4','ContCuentaController@store4')->name('contcuenta.store4');
Route::post('store5','ContCuentaController@store5')->name('contcuenta.store5');
Route::get('edit2/{id}','ContCuentaController@edit2')->name('contcuenta.edit2');
Route::get('edit3/{id}','ContCuentaController@edit3')->name('contcuenta.edit3');
Route::get('edit4/{id}','ContCuentaController@edit4')->name('contcuenta.edit4');
Route::get('edit5/{id}','ContCuentaController@edit5')->name('contcuenta.edit5');
Route::post('update2','ContCuentaController@update2')->name('contcuenta.update2');
Route::post('update3','ContCuentaController@update3')->name('contcuenta.update3');
Route::post('update4','ContCuentaController@update4')->name('contcuenta.update4');
Route::post('update5','ContCuentaController@update5')->name('contcuenta.update5');
Route::delete('destroy2/{id}','ContCuentaController@destroy2')->name('contcuenta.destroy2');
Route::delete('destroy3/{id}','ContCuentaController@destroy3')->name('contcuenta.destroy3');
Route::delete('destroy4/{id}','ContCuentaController@destroy4')->name('contcuenta.destroy4');
Route::delete('destroy5/{id}','ContCuentaController@destroy5')->name('contcuenta.destroy5');

Route::get('/get-prestatarios', 'DropdownController@getPrestatarios');
Route::get('/get-prestamos/{prestatario}', 'DropdownController@getPrestamos');


//RUTAS PARA REPORTERIA
Route::get('dominioPrueba.pdf', 'DominioController@generatePDF');

Route::get('partidacPrueba.pdf', 'PartidacController@generatePDF')->name('reportePartidac');
Route::get('partidacPrueba.pdf2', 'PartidacController@generatePDF2')->name('reportePartidacr');
Route::get('partidacPrueba.pdf3/{id}', 'PartidacController@generatePDF3')->name('reportePartidac3');
Route::get('partidacPrueba.pdf4/{id}/{status}', 'PartidacController@generatePDF4')->name('reportePartidac4');
Route::get('libroMayor.pdf5/{id}', 'PartidacController@generatePDF5')->name('libroMayorpdf');
Route::get('partidac.pdf6/{fechai}/{fechaf}/{cuenta}', 'PartidacController@generatePDF6')->name('partidashpdf');
Route::get('/pagoPrueba.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF')->name('reportePago');
Route::get('/pagoPrueba2.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF2')->name('reportePago2');
Route::get('/pagoPrueba3.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF3')->name('reportePago3');
Route::get('/pagoPrueba4.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF4')->name('reportePago4');
Route::get('/pagoPrueba5.pdf/{idprest}/{fechadepago}', 'PagoController@generatePDF5')->name('reportePago5');
Route::get('/jsonpago/{idprest}/{fechadepago}', 'PagoController@jsonp')->name('jsonpago');
Route::get('contribuyentePrueba.pdf', 'ContribuyenteController@generatePDF');
Route::get('catcuentaPrueba.pdf', 'CatcuentaController@generatePDF');
Route::get('contcuentaPrueba.pdf', 'ContCuentaController@generatePDF');
Route::get('libcomprasPrueba.pdf', 'LibcomprasController@generatePDF');
Route::get('/prestamoPrueba.pdf/{id}', 'PrestamoController@generatePDF')->name('reportePre');
Route::get('/prestamoPrueba2.pdf/{id}', 'PrestamoController@generatePDF2')->name('reportePre2');

Route::get('/exportPrestamo/{id}', 'PrestamoController@exportExcel')->name('excelPrestamo');
Route::get('/exportLibcompras/{ccf}', 'LibcomprasController@exportExcel')->name('excelLibcompras');
Route::get('/exportLibventascs/{ccf}', 'LibventascsController@exportExcel')->name('excelLibventascs');
Route::get('/detalle/{periodo}', 'LibventasController@detalle')->name('detalleVentas');
Route::get('/exportLibrocuenta/{fechai}/{fechaf}/{cuenta}', 'PartidacController@exportExcelp')->name('excelLibroCuenta');
Route::get('exportPartidac', 'PartidacController@exportExcel')->name('excelPartidac');
Route::get('exportPartidac2', 'PartidacController@exportExcel2')->name('excelPartidacr');
Route::get('cierre', 'PartidacController@cierre')->name('cierre');
Route::get('procesoCierre', 'PartidacController@procesoCierre')->name('procesoCierre');
Route::get('reproceso', 'PartidacController@Reproceso')->name('reproceso');
Route::get('vreproceso', 'PartidacController@Vreproceso')->name('vreproceso');
Route::get('partidash', 'PartidacController@Partidash')->name('historialdePartidas');

Route::get('reportes', 'ReporteController@Index')->name('reportes.index');
Route::get('reportePrestamo.pdf', 'ReporteController@generatePDF')->name('reportePrestamop');
Route::get('exportPrestamo', 'ReporteController@exportExcel')->name('reportePrestamoe');

Route::get('especieAmenazada.pdf', 'EspecieAmenazadaController@generatePDF');
Route::get('reporteTaxonomia.pdf', 'TaxonomiaController@generatePDF');
Route::get('/reportePDF.pdf/{id}', 'EspecimenController@generatePDF');
Route::get('/reporteEspecie/{idReino}', 'EspecieController@reportePDF')->name('reporte2');

app/ContRubro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;


class Contrubro extends Model
{
    use LogsActivity;

    protected $fillable = ['rubro', 'padre', 'hijo', 'tipo', 'rubroDesc', 'estatus', 'estatus2', 'saldoInicial', 'debe', 'haber', 'saldo', 'fechaCierre', 'fechaUltCierre'];
    protected $dates = ['created_at','updated_at'];

    public function scopeNombre($query, $nombre)
    {
        return $query->where('rubroDesc', 'LIKE', "%$nombre%");
    }
 }

resources/views/contrubro/create.blade.php
@extends('layout')
@section('container')
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h3 style="text-align:center"> DATOS DE LA CUENTA</h3>
      <br>
      {{ Form::model($contcuentas,['route'=>['contcuenta.store'], 'method'=>'POST']) }}
        @include('contcuenta.form_master')
      {{ form::close() }}
    </div>
  </div>
@endsection

resources/views/contrubro/form_master.blade.php
<div class="row">
  <br>

<div class="col-sm-5">
      {!! form::label('Cuenta a la que pertenezca:') !!}
    </div>
   
   <div class="col-sm-5">
      <select name="padre" class="form-control" >
                <option disabled selected>Seleccione cuenta </option>
                   @foreach($contcuentas as $contcuenta)  
                      <option value="{{$contcuenta->id}}">{{$contcuenta->cuenta}} - {{$contcuenta->rubroDesc}}</option>
                @endforeach
            </select>
      
          <div class="help-block" > 
          {{ $errors->first('idGenero', 'Debe seleccionar una opción') }}
      </div>          
 </div>
    <br>


    <div class="col-sm-5">
      {!! form::label('Cuenta:') !!}
    </div>
     <div class="col-sm-5">
      <div class="form-group {{ $errors->has('cuenta') ? 'has-error' : "" }}">
       <i>{{ Form::text('cuenta',NULL, ['class'=>'form-control', 'id'=>'cuenta', 'placeholder'=>'Cuenta','maxlength' => 80]) }} </i> 
        <div class="help-block"> 
          <strong>{{ $errors->first('cuenta', 'Ingrese nombre correctamente') }}</strong>
      </div>
    </div>
  </div>

    <div class="col-sm-5">
      {!! form::label('Rubro / Descripcion de la cuenta:') !!}
    </div>
     <div class="col-sm-5">
      <div class="form-group {{ $errors->has('rubroDesc') ? 'has-error' : "" }}">
       <i>{{ Form::text('rubroDesc',NULL, ['class'=>'form-control', 'id'=>'rubroDesc', 'placeholder'=>'Descripcion de la cuenta','maxlength' => 180]) }} </i> 
        <div class="help-block"> 
          <strong>{{ $errors->first('rubroDesc', 'Ingrese nombre correctamente') }}</strong>
      </div>
    </div>
  </div>

    <div class="col-sm-5">
      {!! form::label('estatus','Estado') !!}
    </div>
    <div class="col-sm-5">
        <i>{{ Form::select('estatus', ['1'=>'Activo', '0'=>'Inactivo'], null, ['class'=>'form-control']) }}</i>
      </div>

      <input type="hidden" name="saldoInicial" value=0>
      <input type="hidden" name="debe" value=0>
      <input type="hidden" name="haber" value=0>
      <input type="hidden" name="saldo" value=0>
 
    <br>
       <div class="form-group text-center" >
      {{ Form::button(isset($model)? 'Update' : 'Guardar' , ['class'=>'btn btn-success btn-lg','type'=>'submit']) }}
      <a class="btn btn-danger btn-lg" href="{{ route('contcuenta.index') }}">Cancelar</a>
    </div>
    </div>

resources/views/contrubro/form_master2.blade.php
   <div class="row">

    <div class="col-sm-5">
      {!! form::label('Cuenta a la que pertenezca:') !!}
    </div>
   
   <div class="col-sm-5">
      <select name="padre" class="form-control" >
                <option disabled selected>Seleccione cuenta </option>
                   @foreach($contcuentas as $contcuenta)  
                      <option value="{{$contcuenta->id}}">{{$contcuenta->cuenta}} - {{$contcuenta->rubroDesc}}</option>
                @endforeach
            </select>
      
          <div class="help-block" > 
          {{ $errors->first('idGenero', 'Debe seleccionar una opción') }}
      </div>          
 </div>

    <div class="col-sm-5">
      {!! form::label('Subcuenta:') !!}
    </div>
     <div class="col-sm-5">
      <div class="form-group {{ $errors->has('subcuenta') ? 'has-error' : "" }}">
       <i>{{ Form::text('subcuenta',NULL, ['class'=>'form-control', 'id'=>'subcuenta', 'placeholder'=>'Subcuenta','maxlength' => 80]) }} </i> 
        <div class="help-block"> 
          <strong>{{ $errors->first('subcuenta', 'Ingrese nombre correctamente') }}</strong>
      </div>
    </div>
  </div>

    <div class="col-sm-5">
      {!! form::label('Rubro / Descripcion de la Subcuenta:') !!}
    </div>
     <div class="col-sm-5">
      <div class="form-group {{ $errors->has('rubroDesc') ? 'has-error' : "" }}">
       <i>{{ Form::text('rubroDesc',NULL, ['class'=>'form-control', 'id'=>'rubroDesc', 'placeholder'=>'Descripcion de la Subcuenta','maxlength' => 80]) }} </i> 
        <div class="help-block"> 
          <strong>{{ $errors->first('rubroDesc', 'Ingrese nombre correctamente') }}</strong>
      </div>
    </div>
  </div>

    <div class="col-sm-5">
      {!! form::label('estatus','Estado') !!}
    </div>
    <div class="col-sm-5">
        <i>{{ Form::select('estatus', ['1'=>'Activo', '0'=>'Inactivo'], null, ['class'=>'form-control']) }}</i>
      </div>

      <input type="hidden" name="saldoInicial" value=0>
      <input type="hidden" name="debe" value=0>
      <input type="hidden" name="haber" value=0>
      <input type="hidden" name="saldo" value=0>
    </div>
 
    <br>
       <div class="form-group text-center" >
      {{ Form::button(isset($model)? 'Update' : 'Guardar' , ['class'=>'btn btn-success btn-lg','type'=>'submit']) }}
      <a class="btn btn-danger btn-lg" href="{{ route('contcuenta.index') }}">Cancelar</a>
    </div>

resources/views/contrubro/form_master3.blade.php
   <div class="row">

    <div class="col-sm-5">
      {!! form::label('Cuenta a la que pertenezca:') !!}
    </div>
   <div class="col-sm-5">
      <select name="padre" class="form-control" >
                <option disabled selected>Seleccione Subcuenta </option>
                   @foreach($contsubcuentas as $contsubcuenta)  
                      <option value="{{$contsubcuenta->id}}">{{$contsubcuenta->subcuenta}} - {{$contsubcuenta->rubroDesc}}</option>
                @endforeach
            </select>
      
          <div class="help-block" > 
          {{ $errors->first('idGenero', 'Debe seleccionar una opción') }}
      </div>          
 </div>

    <div class="col-sm-5">
      {!! form::label('Cuenta detalle:') !!}
    </div>
     <div class="col-sm-5">
      <div class="form-group {{ $errors->has('cuentaDetalle') ? 'has-error' : "" }}">
       <i>{{ Form::text('cuentaDetalle',NULL, ['class'=>'form-control', 'id'=>'cuentaDetalle', 'placeholder'=>'Cuenta Detalle','maxlength' => 80]) }} </i> 
        <div class="help-block"> 
          <strong>{{ $errors->first('cuentaDetalle', 'Ingrese nombre correctamente') }}</strong>
      </div>
    </div>
  </div>

    <div class="col-sm-5">
      {!! form::label('Rubro / Descripcion de la Subcuenta:') !!}
    </div>
     <div class="col-sm-5">
      <div class="form-group {{ $errors->has('rubroDesc') ? 'has-error' : "" }}">
       <i>{{ Form::text('rubroDesc',NULL, ['class'=>'form-control', 'id'=>'rubroDesc', 'placeholder'=>'Descripcion de la Subcuenta','maxlength' => 80]) }} </i> 
        <div class="help-block"> 
          <strong>{{ $errors->first('rubroDesc', 'Ingrese nombre correctamente') }}</strong>
      </div>
    </div>
  </div>

    <div class="col-sm-5">
      {!! form::label('estatus','Estado') !!}
    </div>
    <div class="col-sm-5">
        <i>{{ Form::select('estatus', ['1'=>'Activo', '0'=>'Inactivo'], null, ['class'=>'form-control']) }}</i>
      </div>

      <input type="hidden" name="saldoInicial" value=0>
      <input type="hidden" name="debe" value=0>
      <input type="hidden" name="haber" value=0>
      <input type="hidden" name="saldo" value=0>
    </div>
 
    <br>
       <div class="form-group text-center" >
      {{ Form::button(isset($model)? 'Update' : 'Guardar' , ['class'=>'btn btn-success btn-lg','type'=>'submit']) }}
      <a class="btn btn-danger btn-lg" href="{{ route('catcuenta.index') }}">Cancelar</a>
    </div>

resources/views/contrubro/index.blade.php
@extends ('layout')
@section('header')
<header style="background-image: url('startbootstrap-clean-blog-gh-pages/assets/img/titulos.jpg'); opacity: 0.8;"><h2 style="color: white; font-family: sans-serif; font-size: 58px; text-align: center;">Gestion de cuentas</h2>
  </header>
@endsection
@section('container')
 <br>
  @if ($errors->any())
   <div class="alert alert-danger">
  
          <p>Debe ingresar datos válidos</p>
     
   </div>
  @endif

  <div class="row"> 
       <div class="col-md-8">
        @can('Dominios')
        <a href="{{route('contcuenta.create')}}" class="btn btn-success btn-lg">
            <i class="glyphicon glyphicon-plus"> Nueva Cuenta</i>
        </a>
        <a href="{{route('contcuenta.create2')}}" class="btn btn-success btn-lg">
            <i class="glyphicon glyphicon-plus"> Nueva Subcuenta</i>
        </a>
        <a href="{{route('contcuenta.create3')}}" class="btn btn-success btn-lg">
            <i class="glyphicon glyphicon-plus"> Nueva Cuenta Detalle</i>
        </a>
        @endcan
        </div>
        <div class="col-md-4">
         {!! Form::open(['route'=>'especimen.index', 'method'=>'GET', 'class'=>'navbar-form pull-right', 'role'=>'search'])!!}
        <div class="input-group"> 
           {!! Form::text('codigoEspecimen', null, ['class'=>'form-control', 'placeholder'=>'Buscar'])!!}
           <button type="submit" class="btn-secondary btn-sm" data-toggle="tooltip" data-placement="top" title="Buscar">Buscar</button>
        {!! Form::close()!!}
        </div>
        <br>
      
      </div>
      <div class="col-md-12" style="text-align:right;">
          <a href="contcuentaPrueba.pdf" class="btn-info btn-sm" target="_blank" >Generar PDF</a>
      </div> 
      </div>
 
      <br>
  <table class="table table-striped" style="text-align:center" >
    <tr>
      <th with="80px">No</th>
      <th style="text-align:center">Cuenta</th>
      <th style="text-align:center">Subcuenta</th>
      <th style="text-align:center">Cuenta Detalle</th>
      <th style="text-align:center">rubroDesc</th>
      <th style="text-align:center">Acciones</th>
    </tr>
    <?php $no=1;
     ?>
    @foreach ($contcuentas as $key => $value)
    <tr>
        <td>{{$no++}}</td>
        <td>{{ $value->cuenta }}</td>
        <td>{{ $value->subcuenta }}</td>
        <td>{{ $value->cuentaDetalle }}</td>
        <td>{{ $value->rubroDesc }}</td>
        <td>
          <a class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="top" title="Detalles" href="{{route('contcuenta.show',$value->id)}}">
              <i class="glyphicon glyphicon-list-alt">Detalles</i></a>
          @can('Editar Dominio')
          <a class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Editar" href="{{route('contcuenta.edit',$value->id)}}">
              <i class="glyphicon glyphicon-pencil">Editar</i></a>
          @endcan
          @can('Eliminar Dominio')
            {!! Form::open(['method' => 'DELETE','route' => ['contcuenta.destroy', $value->id],'style'=>'display:inline', 'class'=>'formulario-eliminar']) !!}
              <button type="submit" data-toggle="tooltip" data-placement="top" title="Eliminar" style="display: inline;" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash" >Eliminar</i></button>
            {!! Form::close() !!}
          @endcan
        </td>
      </tr>


      @foreach ($contsubcuentas as $key => $value2)
      @if($value->id == $value2->padre)
    <tr>
        <td>{{$no++}}</td>
        <td>{{ $value2->cuenta }}</td>
        <td>{{ $value2->subcuenta }}</td>
        <td>{{ $value2->cuentaDetalle }}</td>
        <td>{{ $value2->rubroDesc }}</td>
        <td>
          <a class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="top" title="Detalles" href="{{route('contcuenta.show',$value2->id)}}">
              <i class="glyphicon glyphicon-list-alt">Detalles</i></a>
          @can('Editar Dominio')
          <a class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Editar" href="{{route('contcuenta.edit2',$value2->id)}}">
              <i class="glyphicon glyphicon-pencil">Editar</i></a>
          @endcan
          @can('Eliminar Dominio')
            {!! Form::open(['method' => 'DELETE','route' => ['contcuenta.destroy2', $value2->id],'style'=>'display:inline', 'class'=>'formulario-eliminar']) !!}
              <button type="submit" data-toggle="tooltip" data-placement="top" title="Eliminar" style="display: inline;" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash" >Eliminar</i></button>
            {!! Form::close() !!}
          @endcan
        </td>
      </tr>
      


      @foreach ($contcuentadetalles as $key => $value3)
      @if($value2->id == $value3->padre)
    <tr>
        <td>{{$no++}}</td>
        <td>{{ $value3->cuenta }}</td>
        <td>{{ $value3->subcuenta }}</td>
        <td>{{ $value3->cuentaDetalle }}</td>
        <td>{{ $value3->rubroDesc }}</td>
        <td>
          <a class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="top" title="Detalles" href="{{route('contcuenta.show',$value3->id)}}">
              <i class="glyphicon glyphicon-list-alt">Detalles</i></a>
          @can('Editar Dominio')
          <a class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Editar" href="{{route('contcuenta.edit3',$value3->id)}}">
              <i class="glyphicon glyphicon-pencil">Editar</i></a>
          @endcan
          @can('Eliminar Dominio')
            {!! Form::open(['method' => 'DELETE','route' => ['contcuenta.destroy3', $value3->id],'style'=>'display:inline', 'class'=>'formulario-eliminar']) !!}
              <button type="submit" data-toggle="tooltip" data-placement="top" title="Eliminar" style="display: inline;" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash" >Eliminar</i></button>
            {!! Form::close() !!}
          @endcan
        </td>
      </tr>
      @endif
    @endforeach
    @endif


    @endforeach


    @endforeach
  </table>
  {!!$contcuentas->render()!!}
 <div class="text-center">
    <a class="btn btn-primary" href="{{ url('/gestion') }}">Regresar</a>
  </div>

  <!--Script para mostrar formulario y Alerta confirmar Guardar con ajax-->
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

    <script type="text/javascript">
      $('.agregar').hide();
       function mostrarFormulario(){
        $('.agregar').show();
       }
$('.agregar').submit(function(e){
     e.preventDefault();Swal.fire({
  title: '¿Está seguro de guardar esta cuenta?',
  showDenyButton: true,
  //showCancelButton: true,
  confirmButtonText: `Guardar`,
  denyButtonText: `Cancelar`,
})
     .then((result) => {
    if (result.isConfirmed) {
     this.submit();
    }
})
});
</script>
<!--Script para Alerta con ajax-->

 <script type="text/javascript">
$('.formulario-eliminar').submit(function(e){
     e.preventDefault();
       Swal.fire({
    title: '¿Está seguro de eliminar permanentemente esta cuenta?',
    /*text: "You won't be able to revert this!",*/
    icon: 'warning',
    showCancelButton: true,
    confirmButtonColor: '#3085d6',
    cancelButtonColor: '#d33',
    confirmButtonText: 'Eliminar',
    cancelButtonText: 'Cancelar'

  }).then((result) => {
    if (result.isConfirmed) {
     this.submit();
    }
})
});

    </script>
@endsection